### ISSUE TITLE
Reorganise Project

### ISSUE THREAD

**Issue by Bikram-ghuku** [Bikram-ghuku/SyncChatServerGo#16]
## Requirements

- [x] Move all backend code to a backend folder (#18)
- [x] Write a Dockerfile to build the backend go project (#18)
- [x] Update Makefile (#18)
- [x] Have two Postgres service for dev and deploy(#18)
